version: '3.8'

services:
  plex-mqtt-bridge:
    build: .
    container_name: plex-mqtt-bridge
    restart: unless-stopped
    ports:
      - "5000:5000"  # Host:Container port mapping
    volumes:
      - ./config.json:/app/config.json:ro
      - ./tracking_data:/app/tracking_data
    environment:
      - TZ=America/New_York  # Set your timezone
      - DEBUG=true  # Enable debug logging for troubleshooting
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Add logging for debugging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


